#!/bin/bash
LOGIN=$(crc console --credentials  -o json  | jq -r .clusterConfig.adminCredentials.password | dos2unix )
URL=$(crc console --credentials  -o json   | jq -r .clusterConfig.url | dos2unix)

echo logging in as kubeadmin at  $URL  
  
oc login --insecure-skip-tls-verify=true -u kubeadmin -p $LOGIN $URL 
  