#!/bin/bash
# start, login a kubeadmin, get the pw for console login
crc start 
crck 
crcpw
crc console  
echo "Disk is configured as $(crc status | grep Disk | xargs  echo | cut -d ' ' -f 5)"
echo "You need to resize if needed"
